In [1]:
# Carregamento de arquivos .csv
import pandas as pd
from pathlib import Path
pasta_csv = Path("../../db/bilheteria/distribuidoras")
arquivos = sorted(pasta_csv.glob("*.csv"))
dataframes = []
for a in arquivos:
  df = pd.read_csv(a, sep=";", low_memory=False)
  dataframes.append(df)

df_original = pd.concat(dataframes, ignore_index=True, sort=False)

In [2]:
df = df_original.copy()
df = df.rename(columns={
  'DATA_EXIBICAO': 'data_exibicao',
  'TITULO_ORIGINAL': 'titulo_original',
  'TITULO_BRASIL': 'titulo_brasil',
  'CPB_ROE': 'cpb_roe',
  'PAIS_OBRA': 'pais_obra',
  'REGISTRO_SALA': 'registro_sala',
  'NOME_SALA': 'nome_sala',
  'PUBLICO': 'publico',
  'REGISTRO_GRUPO_EXIBIDOR': 'registro_grupo_exibidor',
  'REGISTRO_EXIBIDOR': 'registro_exibidor',
  'REGISTRO_COMPLEXO': 'registro_complexo',
  'MUNICIPIO_SALA_COMPLEXO': 'municipio_sala_complexo',
  'UF_SALA_COMPLEXO': 'uf_sala_complexo',
  'RAZAO_SOCIAL_DISTRIBUIDORA': 'razao_social_distribuidora',
  'CNPJ_DISTRIBUIDORA': 'cnpj_distribuidora',
  'NR_PROTOCOLO_ENVIO': 'nr_protocolo_envio',
  'DATA_HORA_ENVIO_PROTOCOLO': 'data_hora_envio_protocolo'
})

In [3]:
df.head(5)

,data_exibicao,titulo_original,titulo_brasil,cpb_roe,pais_obra,registro_sala,nome_sala,publico,registro_grupo_exibidor,registro_exibidor,registro_complexo,municipio_sala_complexo,uf_sala_complexo,razao_social_distribuidora,cnpj_distribuidora,nr_protocolo_envio,data_hora_envio_protocolo
0,01/01/2014,A COLEÇÃO INVISÍVEL,NaN,B1201666700000,BRASIL,NaN,CINE BRASILIA,4,NaN,NaN,NaN,NaN,NaN,PROVIDENCE DISTRIBUIDORA DE FILMES LTDA,08.656.129/0001-64,21014368003314,NaN
1,01/01/2014,A TOUCH OF SIN,UM TOQUE DE PECADO,E1600132700000,CHINA,NaN,CINE CULTURA LIBERTY MALL (SALA 02),0,NaN,NaN,NaN,NaN,NaN,SM DISTRIBUIDORA DE FILMES LTDA,08.257.054/0001-49,31011026001914,NaN
2,01/01/2014,A TOUCH OF SIN,UM TOQUE DE PECADO,E1600132700000,CHINA,NaN,ESPACO UNIB DE CINEMA (SALA 05),62,NaN,NaN,NaN,NaN,NaN,SM DISTRIBUIDORA DE FILMES LTDA,08.257.054/0001-49,31011026001914,NaN
3,01/01/2014,A TOUCH OF SIN,UM TOQUE DE PECADO,E1600132700000,CHINA,5000866.0,ESPAÇO ITAU COUNTRY 8,16,6000029.0,1944.0,2738.0,PORTO ALEGRE,RS,SM DISTRIBUIDORA DE FILMES LTDA,08.257.054/0001-49,31011026001914,NaN
4,01/01/2014,ABOUT TIME,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,5000674.0,ABC PLAZA 6,14,6000018.0,1843.0,896.0,SANTO ANDRÉ,SP,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,00.979.601/0001-98,31006058001814,NaN

In [4]:
# Remoção de coluna 'registro_sala'
# df.drop(columns=['registro_sala'], inplace=True)

In [5]:
# Remoção de coluna 'nome_sala'
df.drop(columns=['nome_sala'], inplace=True)

In [6]:
# Remoção de coluna 'registro_grupo_exibidor'
df.drop(columns=['registro_grupo_exibidor'], inplace=True)

In [7]:
# Remoção de coluna 'registro_exibidor'
df.drop(columns=['registro_exibidor'], inplace=True)

In [8]:
# Remoção de coluna 'registro_complexo'
df.drop(columns=['registro_complexo'], inplace=True)

In [9]:
# Remoção de coluna 'municipio_sala_complexo'
df.drop(columns=['municipio_sala_complexo'], inplace=True)

In [10]:
# Remoção de coluna 'cnpj_distribuidora'
df.drop(columns=['cnpj_distribuidora'], inplace=True)

In [11]:
# Remoção de coluna 'nr_protocolo_envio'
df.drop(columns=['nr_protocolo_envio'], inplace=True)

In [12]:
# Remoção de coluna 'data_hora_envio_protocolo'
df.drop(columns=['data_hora_envio_protocolo'], inplace=True)

In [13]:
# Tratamento de coluna 'data_exibicao'
df['data_exibicao'] = pd.to_datetime(df['data_exibicao'], format='%d/%m/%Y', dayfirst=True, errors='coerce')

# Tratamento de valores nulos

In [14]:
# Tratamento de colunas 'titulo_original' e 'titulo_brasil'
# Pegar todos os registros que não tem 'titulo_brasil' e substituir pelo valor em 'titulo_original'
df['titulo_brasil'].fillna(df['titulo_original'], inplace=True)

/tmp/ipykernel_481805/3284118710.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['titulo_brasil'].fillna(df['titulo_original'], inplace=True)

In [15]:
# Remoção da coluna 'titulo_original'
df.drop(columns=['titulo_original'], inplace=True)

In [16]:
# Renomear 'titulo_brasil' para 'titulo'
df = df.rename(columns={'titulo_brasil': 'titulo'})

In [17]:
# Forçar remoção de espaços nos títulos
df['titulo'] = df['titulo'].str.strip()

In [18]:
# Forçar títulos em caixa alta
df['titulo'] = df['titulo'].str.upper()

In [19]:
# Remoção de valores nulos na coluna 'cpb_roe'
df.dropna(subset=['cpb_roe'], inplace=True)

In [20]:
# Remoção de valores nulos na coluna 'uf_sala_complexo'
df[df['uf_sala_complexo'].isna()]['pais_obra'].value_counts()
df.dropna(subset=['uf_sala_complexo'], inplace=True)

In [21]:
# Remoção de valores nulos na coluna 'registro_sala'
df.dropna(subset=['registro_sala'], inplace=True)

In [22]:
df[df['pais_obra'].isna()]

,data_exibicao,titulo,cpb_roe,pais_obra,registro_sala,publico,uf_sala_complexo,razao_social_distribuidora
2228681,2015-06-18,KURT COBAIN: MONTAGE OF HECK,E1500545700000,NaN,5000794.0,76,SP,CINEMARK BRASIL S.A
2228682,2015-06-18,KURT COBAIN: MONTAGE OF HECK,E1500545700000,NaN,5000337.0,133,RJ,CINEMARK BRASIL S.A
2228683,2015-06-18,KURT COBAIN: MONTAGE OF HECK,E1500545700000,NaN,5002435.0,100,RS,CINEMARK BRASIL S.A
2228684,2015-06-18,KURT COBAIN: MONTAGE OF HECK,E1500545700000,NaN,5004225.0,55,PE,CINEMARK BRASIL S.A
2228685,2015-06-18,KURT COBAIN: MONTAGE OF HECK,E1500545700000,NaN,5002085.0,57,BA,CINEMARK BRASIL S.A
...,...,...,...,...,...,...,...,...
16610264,2024-05-31,THE CHOSEN - OS ESCOLHIDOS - TEMPORADA 4 - PAR...,E2400142000000,NaN,5002198.0,16,RJ,SM DISTRIBUIDORA DE FILMES LTDA
16616282,2024-06-01,THE CHOSEN - OS ESCOLHIDOS - TEMPORADA 4 - PAR...,E2400142000000,NaN,5002198.0,13,RJ,SM DISTRIBUIDORA DE FILMES LTDA
16622324,2024-06-02,THE CHOSEN - OS ESCOLHIDOS - TEMPORADA 4 - PAR...,E2400142000000,NaN,5002198.0,9,RJ,SM DISTRIBUIDORA DE FILMES LTDA
16627445,2024-06-03,THE CHOSEN - OS ESCOLHIDOS - TEMPORADA 4 - PAR...,E2400142000000,NaN,5002198.0,2,RJ,SM DISTRIBUIDORA DE FILMES LTDA
16638455,2024-06-05,THE CHOSEN - OS ESCOLHIDOS - TEMPORADA 4 - PAR...,E2400142000000,NaN,5002198.0,3,RJ,SM DISTRIBUIDORA DE FILMES LTDA

In [23]:
def preenche_pais_obra(registro: str):
  if registro.startswith('E'):
    return 'ESTRANGEIRO'
  else:
    return 'BRASIL'

df['pais_obra'].fillna(preenche_pais_obra, inplace=True)

/tmp/ipykernel_481805/34119419.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['pais_obra'].fillna(preenche_pais_obra, inplace=True)

In [24]:
# Adição de coluna "capacidade_sala" via cruzamento de dados

df_salas = pd.read_csv("../../db/clean/salas-de-exibicao.csv", sep=",")
cap_por_sala = df_salas.set_index('registro_sala')['assentos_sala']
df['registro_sala'] = df['registro_sala'].astype(int)
df['capacidade_sala'] = df['registro_sala'].map(cap_por_sala)

In [25]:
# Remoção de outliers em `publico`
df = df[df['publico'] <= df['capacidade_sala']]

In [26]:
# Exportando DataFrame para .csv tratado
df.to_csv("../../db/clean/bilheteria-distribuidoras.csv", index=False)