# Importação do arquivo .csv

In [7]:
import pandas as pd

def converte_int(dado: str):
  try:
    return int(dado)
  except ValueError:
    return None

df = pd.read_csv("../../db/salas-de-exibicao.csv", sep=";")

# Renomeia colunas para padrão snake_case
df.columns = df.columns.str.lower()

In [8]:
# Filtragem de colunas úteis
df = df[['nome_sala', 'registro_sala', 'assentos_sala', 'uf_complexo', 'situacao_sala']]

In [9]:
df.head()

,nome_sala,registro_sala,assentos_sala,uf_complexo,situacao_sala
0,CINE COMPANY JAGUARIUNA,5003332.0,162.0,SP,FECHADO
1,CINE COMPANY JAGUARIUNA SALA 01,5003331.0,162.0,SP,FECHADO
2,PARK SHOPPING 01,5003401.0,402.0,SP,EM FUNCIONAMENTO
3,PARK SHOPPING 02,5003402.0,370.0,SP,EM FUNCIONAMENTO
4,PARK SHOPPING 03,5003403.0,245.0,SP,EM FUNCIONAMENTO

In [10]:
# Removendo registros onde registro_sala é nulo
df = df.dropna(subset=['registro_sala'])

# Converter registro_sala para inteiro
df['registro_sala'] = df['registro_sala'].astype(int)

In [11]:
# Convertendo `assentos_sala` para inteiro
df['assentos_sala'] = df['assentos_sala'].astype(int)

In [12]:
df.head()

,nome_sala,registro_sala,assentos_sala,uf_complexo,situacao_sala
0,CINE COMPANY JAGUARIUNA,5003332,162,SP,FECHADO
1,CINE COMPANY JAGUARIUNA SALA 01,5003331,162,SP,FECHADO
2,PARK SHOPPING 01,5003401,402,SP,EM FUNCIONAMENTO
3,PARK SHOPPING 02,5003402,370,SP,EM FUNCIONAMENTO
4,PARK SHOPPING 03,5003403,245,SP,EM FUNCIONAMENTO

In [13]:
# Exportando DataFrame para .csv tratado
df.to_csv("../../db/clean/salas-de-exibicao.csv", index=False)