In [37]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import textwrap

df_obras = pd.read_csv('../../db/clean/obras-nao-publicitarias.csv')
df_fsa = pd.read_csv('../../db/cluster/obras_investimento_fsa.csv', sep=";")
df_coproducoes = pd.read_csv('../../db/cluster/coproducoes_brasileiras.csv', sep=";")
df_fomento_ind = pd.read_csv('../../db/cluster/obras_fomento_indireto.csv', sep=";")
df_lanc_comerciais = pd.read_csv('../../db/cluster/lancamentos_comerciais.csv', sep=";") # Remover?
df_dist = pd.read_csv('../../db/clean/bilheteria-distribuidoras.csv', sep=",")
df_exib = pd.read_csv('../../db/clean/bilheteria-exibidoras.csv', sep=",")
df_fsa.columns = df_fsa.columns.str.lower()
df_coproducoes.columns = df_coproducoes.columns.str.lower()
df_fomento_ind.columns = df_fomento_ind.columns.str.lower()
df_lanc_comerciais.columns = df_lanc_comerciais.columns.str.lower()

In [38]:
df_lanc_comerciais

,data_lancamento_obra,titulo_original,cpb_roe,tipo_obra,pais_obra,publico_total,renda_total,razao_social_distribuidora,registro_distribuidora,cnpj_distribuidora
0,26/03/2026,MORTE E VIDA MADALENA,B2400372900000,FICÇÃO,BRASIL,374,"R$ 4.973,27",EMBAUBA FILMES LTDA,23638.0,15.144.532/0001-70
1,06/11/2025,UMA NOVA HISTÓRIA,B2500383600000,FICÇÃO,BRASIL,1180,"R$ 22.046,80",HEAVEN CONTENT LTDA,62174.0,60.240.539/0001-40
2,30/10/2025,A MEMÓRIA DO CHEIRO DAS COISAS,B2500349200000,FICÇÃO,PORTUGAL,13,"R$ 152,51",TREZE DE MAIO DISTRIBUIDORA E PRODUTORA LTDA,52561.0,40.379.968/0001-95
3,30/10/2025,DREAMS,E2500328600000,FICÇÃO,ESTADOS UNIDOS,1799,"R$ 47.248,95",WMIX DISTRIBUIDORA LTDA.,1935.0,03.918.609/0001-32
4,30/10/2025,ENTERRE SEUS MORTOS,B2500154400000,FICÇÃO,BRASIL,1301,"R$ 26.009,28",O2 PRODUÇÕES ARTÍSTICAS E CINEMATOGRÁFICAS LTDA.,63.0,67.431.718/0001-03
...,...,...,...,...,...,...,...,...,...,...
6823,04/01/2009,THE STRANGERS,E1600633000000,FICÇÃO,ESTADOS UNIDOS,291713,"R$ 2.350.017,91",SM DISTRIBUIDORA DE FILMES LTDA,11922.0,08.257.054/0001-49
6824,02/01/2009,SE EU FOSSE VOCÊ 2,B0800958700000,FICÇÃO,BRASIL,29830,"R$ 37.557,00",CANNES PRODUÇÕES LTDA,2250.0,72.672.017/0001-04
6825,02/01/2009,SE EU FOSSE VOCÊ 2,B0800958700000,FICÇÃO,BRASIL,6113251,"R$ 50.545.885,00",FOX FILM DO BRASIL LTDA,256.0,33.110.420/0001-80
6826,01/01/2009,BOLT,E1500346000000,ANIMAÇÃO,ESTADOS UNIDOS,1162616,"R$ 9.590.392,25",COLUMBIA TRISTAR FILMES DO BRASIL LTDA,84.0,00.979.601/0001-98
6827,01/01/2009,LA BELLE PERSONNE,E1600594000000,FICÇÃO,FRANÇA,17207,"R$ 141.070,93",TAG CULTURAL DISTRIBUIDORA DE FILMES LTDA,173.0,03.599.148/0001-82

In [39]:
# Remove os filmes estrangeiros de `df_lanc_comerciais`
df_lanc_comerciais = df_lanc_comerciais[~df_lanc_comerciais['cpb_roe'].str.startswith('E', na=False)]

# Renomeia a coluna `cpb_roe` apenas para `cpb`, já que não há mais registros estrangeiros
df_lanc_comerciais.rename(columns={'cpb_roe': 'cpb'}, inplace=True)

/tmp/ipykernel_2193970/4084595463.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lanc_comerciais.rename(columns={'cpb_roe': 'cpb'}, inplace=True)

In [40]:
# Trata o campo `renda_total`
df_lanc_comerciais = df_lanc_comerciais.copy()
df_lanc_comerciais['renda_total'] = df_lanc_comerciais['renda_total'] \
.str.replace('R$ ', '', regex=False) \
.str.replace('.', '', regex=False) \
.str.replace(',', '.', regex=False) \
.astype(float)

In [41]:
# Remove os filmes estrangeiros de `df_dist`
df_dist = df_dist[~df_dist['cpb_roe'].str.startswith('E', na=False)]

# Renomeia a coluna `cpb_roe` apenas para `cpb`, já que não há mais registros estrangeiros
df_dist.rename(columns={'cpb_roe': 'cpb'}, inplace=True)

In [42]:
# Remove os filmes estrangeiros de `df_exib`
df_exib = df_exib[~df_exib['cpb_roe'].str.startswith('E', na=False)]

# Renomeia a coluna `cpb_roe` apenas para `cpb`, já que não há mais registros estrangeiros
df_exib.rename(columns={'cpb_roe': 'cpb'}, inplace=True)

# Renomeia coluna `sessao`
df_exib.rename(columns={'sessao': 'data_exibicao'}, inplace=True)

In [43]:
df_dist

,data_exibicao,titulo,cpb,pais_obra,registro_sala,publico,uf_sala_complexo,razao_social_distribuidora,capacidade_sala,tipo_filme,ano
93,2014-01-01,ANITA E GARIBALDI,B1301738800000,BRASIL,5002815,0,SC,CINEMATOGRÁFICA POLIFILMES LTDA-ME,244,Brasileiro,2014
94,2014-01-01,ATÉ QUE A SORTE NOS SEPARE 2,B1302035000000,BRASIL,5002040,250,MT,SM DISTRIBUIDORA DE FILMES LTDA,269,Brasileiro,2014
95,2014-01-01,ATÉ QUE A SORTE NOS SEPARE 2,B1302035000000,BRASIL,5000669,73,SP,SM DISTRIBUIDORA DE FILMES LTDA,226,Brasileiro,2014
96,2014-01-01,ATÉ QUE A SORTE NOS SEPARE 2,B1302035000000,BRASIL,5000671,58,SP,SM DISTRIBUIDORA DE FILMES LTDA,165,Brasileiro,2014
97,2014-01-01,ATÉ QUE A SORTE NOS SEPARE 2,B1302035000000,BRASIL,5000672,56,SP,SM DISTRIBUIDORA DE FILMES LTDA,221,Brasileiro,2014
...,...,...,...,...,...,...,...,...,...,...,...
16564266,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5002512,10,SP,VITRINE FILMES LTDA,406,Brasileiro,2025
16564267,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5000062,4,RJ,VITRINE FILMES LTDA,230,Brasileiro,2025
16564268,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5001099,31,RS,VITRINE FILMES LTDA,40,Brasileiro,2025
16564269,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5001791,15,BA,VITRINE FILMES LTDA,125,Brasileiro,2025
16564270,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5000077,26,RJ,VITRINE FILMES LTDA,271,Brasileiro,2025

In [44]:
df_lanc_comerciais

,data_lancamento_obra,titulo_original,cpb,tipo_obra,pais_obra,publico_total,renda_total,razao_social_distribuidora,registro_distribuidora,cnpj_distribuidora
0,26/03/2026,MORTE E VIDA MADALENA,B2400372900000,FICÇÃO,BRASIL,374,4973.27,EMBAUBA FILMES LTDA,23638.0,15.144.532/0001-70
1,06/11/2025,UMA NOVA HISTÓRIA,B2500383600000,FICÇÃO,BRASIL,1180,22046.80,HEAVEN CONTENT LTDA,62174.0,60.240.539/0001-40
2,30/10/2025,A MEMÓRIA DO CHEIRO DAS COISAS,B2500349200000,FICÇÃO,PORTUGAL,13,152.51,TREZE DE MAIO DISTRIBUIDORA E PRODUTORA LTDA,52561.0,40.379.968/0001-95
4,30/10/2025,ENTERRE SEUS MORTOS,B2500154400000,FICÇÃO,BRASIL,1301,26009.28,O2 PRODUÇÕES ARTÍSTICAS E CINEMATOGRÁFICAS LTDA.,63.0,67.431.718/0001-03
8,30/10/2025,NOVIEMBRE,B2500415900000,FICÇÃO,BRASIL,73,861.00,ATELIER W PRODUCOES CINEMATOGRAFICAS LTDA,15202.0,10.468.552/0001-82
...,...,...,...,...,...,...,...,...,...,...
6799,30/01/2009,MENSAGEIRAS DA LUZ - PARTEIRAS DA AMAZÔNIA,B0500216600000,DOCUMENTÁRIO,BRASIL,108,321.12,CINEMATOGRÁFICA POLIFILMES LTDA-ME,2550.0,60.469.871/0001-80
6816,16/01/2009,TITÃS - A VIDA ATÉ PARECE UMA FESTA,B0800925800000,DOCUMENTÁRIO,BRASIL,15211,144600.42,RAIN NETWORK REPRESENTAÇÃO COMERCIAL LTDA,13613.0,07.949.581/0001-51
6821,09/01/2009,O GRILO FELIZ E OS INSETOS GIGANTES,B0800964000000,ANIMAÇÃO,BRASIL,370757,1953751.17,FOX FILM DO BRASIL LTDA,256.0,33.110.420/0001-80
6824,02/01/2009,SE EU FOSSE VOCÊ 2,B0800958700000,FICÇÃO,BRASIL,29830,37557.00,CANNES PRODUÇÕES LTDA,2250.0,72.672.017/0001-04
6825,02/01/2009,SE EU FOSSE VOCÊ 2,B0800958700000,FICÇÃO,BRASIL,6113251,50545885.00,FOX FILM DO BRASIL LTDA,256.0,33.110.420/0001-80

In [45]:
df_fsa.head()

         titulo_original             cpb  numero_contrato_fsa
0    " A PRIMEIRA MISSA"  B1301902100000            212037800
1  "EL HOMBRE QUE CUIDA"  B1800115900000                 1237
2            #FALAGALERA  B1700424900000                  547
3            #FALASÉRIO!  B2500287100000                 3051
4          #PARTIUBRASIL  B1700178200000                  498

In [46]:
df_cluster = pd.DataFrame()
df_cluster = df_obras[['cpb']].copy()
df_cluster.set_index('cpb', inplace=True)
df_cluster['investimento_fsa'] = pd.NA
df_cluster['coproducao'] = pd.NA
df_cluster['fomento_indireto'] = pd.NA
df_cluster['publico_total'] = pd.NA
df_cluster['qtd_sessoes'] = pd.NA
df_cluster['dias_cartaz'] = pd.NA
df_cluster['renda_total'] = pd.NA

In [47]:
# Adiciona valores na coluna `investimento_fsa`
fsa_cpbs = set(df_fsa['cpb'].dropna())
df_cluster['investimento_fsa'] = df_cluster.index.isin(fsa_cpbs)

In [48]:
# Adiciona valores na coluna `coproducao`
coproducao_cpbs = set(df_coproducoes['cpb'].dropna())
df_cluster['coproducao'] = df_cluster.index.isin(coproducao_cpbs)

In [49]:
# Adiciona valores na coluna `fomento_indireto`
fomento_ind_cpbs = set(df_fomento_ind['cpb'].dropna())
df_cluster['fomento_indireto'] = df_cluster.index.isin(fomento_ind_cpbs)

In [50]:
# Adiciona colunas para `cat_duracao`
map_cats = df_obras.set_index('cpb')['cat_duracao']

df_cluster['cat_duracao'] = df_cluster.index.map(map_cats)

df_cluster = pd.get_dummies(df_cluster, columns=['cat_duracao'])
hot_encode_nomes = {
    'cat_duracao_CURTA METRAGEM': 'curta_metragem',
    'cat_duracao_MÉDIA METRAGEM': 'media_metragem',
    'cat_duracao_LONGA METRAGEM': 'longa_metragem'
}
df_cluster = df_cluster.rename(columns=hot_encode_nomes)

In [51]:
# Adiciona a coluna `publico_total`
map_publico_comercial = df_lanc_comerciais.groupby('cpb')['publico_total'].sum()
map_publico_dist = df_dist.groupby('cpb')['publico'].sum()
map_publico_exib = df_exib.groupby('cpb')['publico'].sum()

s_comercial = map_publico_comercial.reindex(df_cluster.index)
s_dist = map_publico_dist.reindex(df_cluster.index)
s_exib = map_publico_exib.reindex(df_cluster.index)

df_cluster['publico_total'] = s_comercial.combine_first(s_dist).combine_first(s_exib)

In [52]:
# Adiciona a coluna `qtd_sessoes`
map_qtd_dist = df_dist.groupby('cpb').size()
map_qtd_exib = df_exib.groupby('cpb').size()

s_qtd_dist = map_qtd_dist.reindex(df_cluster.index)
s_qtd_exib = map_qtd_exib.reindex(df_cluster.index)

df_cluster['qtd_sessoes'] = s_qtd_dist.combine_first(s_qtd_exib)

In [53]:
# Adiciona a coluna `dias_cartaz`
df_dist = df_dist.copy()
df_dist['data_exibicao'] = pd.to_datetime(df_dist['data_exibicao'])
df_exib['data_exibicao'] = pd.to_datetime(df_exib['data_exibicao'])

map_dias_dist = df_dist.groupby('cpb')['data_exibicao'].nunique()
map_dias_exib = df_dist.groupby('cpb')['data_exibicao'].nunique()

s_dias_dist = map_dias_dist.reindex(df_cluster.index)
s_dias_exib = map_dias_exib.reindex(df_cluster.index)

df_cluster['dias_cartaz'] = s_dias_dist.combine_first(s_dias_exib)

In [54]:
# Adiciona a coluna `renda_total`
map_rendas = df_lanc_comerciais.groupby('cpb')['renda_total'].sum()

s_map_rendas = map_rendas.reindex(df_cluster.index)
df_cluster['renda_total'] = s_map_rendas

In [55]:
df_obras

,titulo_original,cpb,tipo_obra,classificacao_obra,duracao_total_minutos,ano_producao_inicial,segmento_destinacao_inicial,requerente,uf_requerente,municipio_requerente,cat_duracao
0,"""SOLO""",B0901120600000,FICÇÃO,BRASILEIRA INDEPENDENTE CONSTITUINTE DE ESPAÇO...,72.0,2009,INDEFINIDO,SP FILMES DE SÃO PAULO LTDA,SP,SÃO PAULO,LONGA METRAGEM
1,"""TANGO""",B0901074000000,NÃO CLASSIFICADA,NÃO INFORMADO,35.7,2009,INDEFINIDO,INTERNACIONAL - PRODUÇÕES DE CINEMA E VÍDEO LTDA,RJ,RIO DE JANEIRO,MÉDIA METRAGEM
2,"1,2,3! ÊXTASE!",B0900987500000,NÃO CLASSIFICADA,NÃO INFORMADO,5.0,2009,INDEFINIDO,CORTEX DIGITAL LTDA,RJ,RIO DE JANEIRO,CURTA METRAGEM
3,1983.. O ANO AZUL,B0901024500000,DOCUMENTÁRIO,BRASILEIRA CONSTITUINTE DE ESPAÇO QUALIFICADO,89.7,2009,INDEFINIDO,INVÍDEO PRODUÇÕES CINEMATOGRÁFICAS LTDA.,RS,PORTO ALEGRE,LONGA METRAGEM
4,1° FESTIVAL DE TEATRO DE RUA DE PORTO ALEGRE,B0901108400000,NÃO CLASSIFICADA,NÃO INFORMADO,41.1,2009,INDEFINIDO,FREDERICO AUGUSTO RUAS DOS SANTOS,RS,PORTO ALEGRE,MÉDIA METRAGEM
...,...,...,...,...,...,...,...,...,...,...,...
33357,É TUDO PARENTE,B2500249300000,DOCUMENTÁRIO,BRASILEIRA INDEPENDENTE CONSTITUINTE DE ESPAÇO...,90.6,2025,SALAS DE EXIBIÇÃO,FABULOSA PRODUCOES LTDA - ME,MG,BELO HORIZONTE,LONGA METRAGEM
33358,ÉRAMOS FELIZES NA CASINHA BRANCA AO PÉ DA SERRA,B2500310100000,DOCUMENTÁRIO,BRASILEIRA INDEPENDENTE CONSTITUINTE DE ESPAÇO...,3.0,2025,OUTROS MERCADOS,50.912.764 FRANCIELITO DA SILVA LIMA,RN,LAGOA NOVA,CURTA METRAGEM
33359,ÊXODO RURAL,B2500143000000,DOCUMENTÁRIO,BRASILEIRA CONSTITUINTE DE ESPAÇO QUALIFICADO,11.8,2025,OUTROS MERCADOS,GABRIELA LACERDA BENELLI,MG,ESPERA FELIZ,CURTA METRAGEM
33360,Ô ABRE ALAS,B2500042000000,VÍDEOMUSICAL,BRASILEIRA INDEPENDENTE CONSTITUINTE DE ESPAÇO...,3.4,2025,VÍDEO POR DEMANDA,AVENIDA LAMPARINA PRODUCOES LTDA,SC,JARAGUÁ DO SUL,CURTA METRAGEM
33361,ÔNIBUS DAS QUATRO,B2500254500000,FICÇÃO,BRASILEIRA CONSTITUINTE DE ESPAÇO QUALIFICADO,8.7,2025,SALAS DE EXIBIÇÃO,CAROLINA GIANNINI VEIRANO,SP,SÃO PAULO,CURTA METRAGEM

In [56]:
df_cluster.dropna().count()

investimento_fsa    1741
coproducao          1741
fomento_indireto    1741
publico_total       1741
qtd_sessoes         1741
dias_cartaz         1741
renda_total         1741
curta_metragem      1741
longa_metragem      1741
media_metragem      1741
dtype: int64

In [57]:
df_cluster.head()

,investimento_fsa,coproducao,fomento_indireto,publico_total,qtd_sessoes,dias_cartaz,renda_total,curta_metragem,longa_metragem,media_metragem
cpb,,,,,,,,,,
B0901120600000,False,False,False,986.0,NaN,NaN,8970.00,False,True,False
B0901074000000,False,False,False,NaN,NaN,NaN,NaN,False,False,True
B0900987500000,False,False,False,NaN,NaN,NaN,NaN,True,False,False
B0901024500000,False,False,False,2313.0,NaN,NaN,23001.98,False,True,False
B0901108400000,False,False,False,NaN,NaN,NaN,NaN,False,False,True