In [128]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import textwrap

df_obras = pd.read_csv('../../db/clean/obras-nao-publicitarias.csv')
df_fsa = pd.read_csv('../../db/cluster/obras_investimento_fsa.csv', sep=";")
df_coproducoes = pd.read_csv('../../db/cluster/coproducoes_brasileiras.csv', sep=";")
df_fomento_ind = pd.read_csv('../../db/cluster/obras_fomento_indireto.csv', sep=";")
df_lanc_comerciais = pd.read_csv('../../db/cluster/lancamentos_comerciais.csv', sep=";") # Remover?
df_bilheteria = pd.read_csv('../../db/clean/bilheteria-distribuidoras.csv', sep=",")
df_fsa.columns = df_fsa.columns.str.lower()
df_coproducoes.columns = df_coproducoes.columns.str.lower()
df_fomento_ind.columns = df_fomento_ind.columns.str.lower()
df_lanc_comerciais.columns = df_lanc_comerciais.columns.str.lower()

In [129]:
df_bilheteria

,data_exibicao,titulo,cpb_roe,pais_obra,registro_sala,publico,uf_sala_complexo,razao_social_distribuidora,capacidade_sala,tipo_filme,ano
0,2014-01-01,UM TOQUE DE PECADO,E1600132700000,CHINA,5000866,16,RS,SM DISTRIBUIDORA DE FILMES LTDA,98,Estrangeiro,2014
1,2014-01-01,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,5000674,14,SP,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,221,Estrangeiro,2014
2,2014-01-01,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,5000795,60,SP,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,119,Estrangeiro,2014
3,2014-01-01,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,5003834,0,SC,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,201,Estrangeiro,2014
4,2014-01-01,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,5003845,0,SP,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,225,Estrangeiro,2014
...,...,...,...,...,...,...,...,...,...,...,...
16564789,2025-09-06,MULHOLLAND DRIVE - CIDADE DOS SONHOS,E1700486000000,ESTADOS UNIDOS,5000848,18,RJ,RETRATO FILMES LTDA,251,Estrangeiro,2025
16564790,2025-09-07,MULHOLLAND DRIVE - CIDADE DOS SONHOS,E1700486000000,ESTADOS UNIDOS,5000848,17,RJ,RETRATO FILMES LTDA,251,Estrangeiro,2025
16564791,2025-09-08,MULHOLLAND DRIVE - CIDADE DOS SONHOS,E1700486000000,ESTADOS UNIDOS,5000848,2,RJ,RETRATO FILMES LTDA,251,Estrangeiro,2025
16564792,2025-09-09,MULHOLLAND DRIVE - CIDADE DOS SONHOS,E1700486000000,ESTADOS UNIDOS,5000848,2,RJ,RETRATO FILMES LTDA,251,Estrangeiro,2025
16564793,2025-09-10,MULHOLLAND DRIVE - CIDADE DOS SONHOS,E1700486000000,ESTADOS UNIDOS,5000848,9,RJ,RETRATO FILMES LTDA,251,Estrangeiro,2025

In [130]:
# Remove os filmes estrangeiros de `df_lanc_comerciais`
df_lanc_comerciais = df_lanc_comerciais[~df_lanc_comerciais['cpb_roe'].str.startswith('E', na=False)]

# Renomeia a coluna `cpb_roe` apenas para `cpb`, já que não há mais registros estrangeiros
df_lanc_comerciais.rename(columns={'cpb_roe': 'cpb'}, inplace=True)

In [131]:
# Remove os filmes estrangeiros de `df_bilheteria`
df_bilheteria = df_bilheteria[~df_bilheteria['cpb_roe'].str.startswith('E', na=False)]

# Renomeia a coluna `cpb_roe` apenas para `cpb`, já que não há mais registros estrangeiros
df_bilheteria.rename(columns={'cpb_roe': 'cpb'}, inplace=True)

/tmp/ipykernel_964590/3062950265.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_bilheteria.rename(columns={'cpb_roe': 'cpb'}, inplace=True)

In [132]:
df_bilheteria

,data_exibicao,titulo,cpb,pais_obra,registro_sala,publico,uf_sala_complexo,razao_social_distribuidora,capacidade_sala,tipo_filme,ano
93,2014-01-01,ANITA E GARIBALDI,B1301738800000,BRASIL,5002815,0,SC,CINEMATOGRÁFICA POLIFILMES LTDA-ME,244,Brasileiro,2014
94,2014-01-01,ATÉ QUE A SORTE NOS SEPARE 2,B1302035000000,BRASIL,5002040,250,MT,SM DISTRIBUIDORA DE FILMES LTDA,269,Brasileiro,2014
95,2014-01-01,ATÉ QUE A SORTE NOS SEPARE 2,B1302035000000,BRASIL,5000669,73,SP,SM DISTRIBUIDORA DE FILMES LTDA,226,Brasileiro,2014
96,2014-01-01,ATÉ QUE A SORTE NOS SEPARE 2,B1302035000000,BRASIL,5000671,58,SP,SM DISTRIBUIDORA DE FILMES LTDA,165,Brasileiro,2014
97,2014-01-01,ATÉ QUE A SORTE NOS SEPARE 2,B1302035000000,BRASIL,5000672,56,SP,SM DISTRIBUIDORA DE FILMES LTDA,221,Brasileiro,2014
...,...,...,...,...,...,...,...,...,...,...,...
16564266,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5002512,10,SP,VITRINE FILMES LTDA,406,Brasileiro,2025
16564267,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5000062,4,RJ,VITRINE FILMES LTDA,230,Brasileiro,2025
16564268,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5001099,31,RS,VITRINE FILMES LTDA,40,Brasileiro,2025
16564269,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5001791,15,BA,VITRINE FILMES LTDA,125,Brasileiro,2025
16564270,2025-08-31,UM LOBO ENTRE OS CISNES,B2400495700000,BRASIL,5000077,26,RJ,VITRINE FILMES LTDA,271,Brasileiro,2025

In [133]:
df_lanc_comerciais

,data_lancamento_obra,titulo_original,cpb,tipo_obra,pais_obra,publico_total,renda_total,razao_social_distribuidora,registro_distribuidora,cnpj_distribuidora
0,26/03/2026,MORTE E VIDA MADALENA,B2400372900000,FICÇÃO,BRASIL,374,"R$ 4.973,27",EMBAUBA FILMES LTDA,23638.0,15.144.532/0001-70
1,06/11/2025,UMA NOVA HISTÓRIA,B2500383600000,FICÇÃO,BRASIL,1180,"R$ 22.046,80",HEAVEN CONTENT LTDA,62174.0,60.240.539/0001-40
2,30/10/2025,A MEMÓRIA DO CHEIRO DAS COISAS,B2500349200000,FICÇÃO,PORTUGAL,13,"R$ 152,51",TREZE DE MAIO DISTRIBUIDORA E PRODUTORA LTDA,52561.0,40.379.968/0001-95
4,30/10/2025,ENTERRE SEUS MORTOS,B2500154400000,FICÇÃO,BRASIL,1301,"R$ 26.009,28",O2 PRODUÇÕES ARTÍSTICAS E CINEMATOGRÁFICAS LTDA.,63.0,67.431.718/0001-03
8,30/10/2025,NOVIEMBRE,B2500415900000,FICÇÃO,BRASIL,73,"R$ 861,00",ATELIER W PRODUCOES CINEMATOGRAFICAS LTDA,15202.0,10.468.552/0001-82
...,...,...,...,...,...,...,...,...,...,...
6799,30/01/2009,MENSAGEIRAS DA LUZ - PARTEIRAS DA AMAZÔNIA,B0500216600000,DOCUMENTÁRIO,BRASIL,108,"R$ 321,12",CINEMATOGRÁFICA POLIFILMES LTDA-ME,2550.0,60.469.871/0001-80
6816,16/01/2009,TITÃS - A VIDA ATÉ PARECE UMA FESTA,B0800925800000,DOCUMENTÁRIO,BRASIL,15211,"R$ 144.600,42",RAIN NETWORK REPRESENTAÇÃO COMERCIAL LTDA,13613.0,07.949.581/0001-51
6821,09/01/2009,O GRILO FELIZ E OS INSETOS GIGANTES,B0800964000000,ANIMAÇÃO,BRASIL,370757,"R$ 1.953.751,17",FOX FILM DO BRASIL LTDA,256.0,33.110.420/0001-80
6824,02/01/2009,SE EU FOSSE VOCÊ 2,B0800958700000,FICÇÃO,BRASIL,29830,"R$ 37.557,00",CANNES PRODUÇÕES LTDA,2250.0,72.672.017/0001-04
6825,02/01/2009,SE EU FOSSE VOCÊ 2,B0800958700000,FICÇÃO,BRASIL,6113251,"R$ 50.545.885,00",FOX FILM DO BRASIL LTDA,256.0,33.110.420/0001-80

In [134]:
df_fsa.head()

         titulo_original             cpb  numero_contrato_fsa
0    " A PRIMEIRA MISSA"  B1301902100000            212037800
1  "EL HOMBRE QUE CUIDA"  B1800115900000                 1237
2            #FALAGALERA  B1700424900000                  547
3            #FALASÉRIO!  B2500287100000                 3051
4          #PARTIUBRASIL  B1700178200000                  498

In [135]:
df_cluster = pd.DataFrame()
df_cluster = df_obras[['cpb']].copy()
df_cluster.set_index('cpb', inplace=True)
df_cluster['investimento_fsa'] = pd.NA
df_cluster['coproducao'] = pd.NA
df_cluster['fomento_indireto'] = pd.NA
df_cluster['publico_total'] = pd.NA

In [136]:
# Adiciona valores na coluna `investimento_fsa`
fsa_cpbs = set(df_fsa['cpb'].dropna())
df_cluster['investimento_fsa'] = df_cluster.index.isin(fsa_cpbs)

In [137]:
# Adiciona valores na coluna `coproducao`
coproducao_cpbs = set(df_coproducoes['cpb'].dropna())
df_cluster['coproducao'] = df_cluster.index.isin(coproducao_cpbs)

In [138]:
# Adiciona valores na coluna `fomento_indireto`
fomento_ind_cpbs = set(df_fomento_ind['cpb'].dropna())
df_cluster['fomento_indireto'] = df_cluster.index.isin(fomento_ind_cpbs)

In [143]:
# Adiciona a coluna `publico_total`
map_publico_comercial = df_lanc_comerciais.groupby('cpb')['publico_total'].sum()
map_publico_bilheteria = df_bilheteria.groupby('cpb')['publico'].sum()

s_comercial = map_publico_comercial.reindex(df_cluster.index)
s_bilheteria = map_publico_bilheteria.reindex(df_cluster.index)

df_cluster['publico_total'] = s_comercial.combine_first(s_bilheteria)

In [145]:
df_cluster['publico_total'].info()

<class 'pandas.core.series.Series'>
Index: 33362 entries, B0901120600000 to B2500254500000
Series name: publico_total
Non-Null Count  Dtype
--------------  -----
2152 non-null   float64
dtypes: float64(1)
memory usage: 521.3+ KB