In [112]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import textwrap

df_obras = pd.read_csv('../../db/clean/obras-nao-publicitarias.csv')
df_fsa = pd.read_csv('../../db/cluster/obras_investimento_fsa.csv', sep=";")
df_fsa.columns = df_fsa.columns.str.lower()

In [113]:
df_fsa.head()

         titulo_original             cpb  numero_contrato_fsa
0    " A PRIMEIRA MISSA"  B1301902100000            212037800
1  "EL HOMBRE QUE CUIDA"  B1800115900000                 1237
2            #FALAGALERA  B1700424900000                  547
3            #FALASÉRIO!  B2500287100000                 3051
4          #PARTIUBRASIL  B1700178200000                  498

In [114]:
df_cluster = pd.DataFrame()
df_cluster = df_obras[['cpb']].copy()
df_cluster.set_index('cpb', inplace=True)
df_cluster['investimento_fsa'] = pd.NA

In [ ]:
# Adiciona valores na coluna `investimento_fsa`
fsa_cpbs = set(df_fsa['cpb'].dropna())
df_cluster['investimento_fsa'] = df_cluster.index.isin(fsa_cpbs)

In [120]:
df_cluster.head(100)

                investimento_fsa
cpb
B0901120600000             False
B0901074000000             False
B0900987500000             False
B0901024500000             False
B0901108400000             False
...                          ...
B0901114600000             False
B0901079000000             False
B0901122400000             False
B0901031700000             False
B0901095600000             False

[100 rows x 1 columns]