In [3]:
# Carregamento de arquivos .csv
import pandas as pd
from pathlib import Path
pasta_csv = Path("../db/bilheteria/distribuidoras")
arquivos = sorted(pasta_csv.glob("*.csv"))
dataframes = []
for a in arquivos:
  df = pd.read_csv(a, sep=";", low_memory=False)
  dataframes.append(df)

df_original = pd.concat(dataframes, ignore_index=True, sort=False)

In [4]:
df = df_original.copy()
df = df.rename(columns={
  'DATA_EXIBICAO': 'data_exibicao',
  'TITULO_ORIGINAL': 'titulo_original',
  'TITULO_BRASIL': 'titulo_brasil',
  'CPB_ROE': 'cpb_roe',
  'PAIS_OBRA': 'pais_obra',
  'REGISTRO_SALA': 'registro_sala',
  'NOME_SALA': 'nome_sala',
  'PUBLICO': 'publico',
  'REGISTRO_GRUPO_EXIBIDOR': 'registro_grupo_exibidor',
  'REGISTRO_EXIBIDOR': 'registro_exibidor',
  'REGISTRO_COMPLEXO': 'registro_complexo',
  'MUNICIPIO_SALA_COMPLEXO': 'municipio_sala_complexo',
  'UF_SALA_COMPLEXO': 'uf_sala_complexo',
  'RAZAO_SOCIAL_DISTRIBUIDORA': 'razao_social_distribuidora',
  'CNPJ_DISTRIBUIDORA': 'cnpj_distribuidora',
  'NR_PROTOCOLO_ENVIO': 'nr_protocolo_envio',
  'DATA_HORA_ENVIO_PROTOCOLO': 'data_hora_envio_protocolo'
})

In [5]:
display(df.head(10))

,data_exibicao,titulo_original,titulo_brasil,cpb_roe,pais_obra,registro_sala,nome_sala,publico,registro_grupo_exibidor,registro_exibidor,registro_complexo,municipio_sala_complexo,uf_sala_complexo,razao_social_distribuidora,cnpj_distribuidora,nr_protocolo_envio,data_hora_envio_protocolo
0,01/01/2014,A COLEÇÃO INVISÍVEL,NaN,B1201666700000,BRASIL,NaN,CINE BRASILIA,4,NaN,NaN,NaN,NaN,NaN,PROVIDENCE DISTRIBUIDORA DE FILMES LTDA,08.656.129/0001-64,21014368003314,NaN
1,01/01/2014,A TOUCH OF SIN,UM TOQUE DE PECADO,E1600132700000,CHINA,NaN,CINE CULTURA LIBERTY MALL (SALA 02),0,NaN,NaN,NaN,NaN,NaN,SM DISTRIBUIDORA DE FILMES LTDA,08.257.054/0001-49,31011026001914,NaN
2,01/01/2014,A TOUCH OF SIN,UM TOQUE DE PECADO,E1600132700000,CHINA,NaN,ESPACO UNIB DE CINEMA (SALA 05),62,NaN,NaN,NaN,NaN,NaN,SM DISTRIBUIDORA DE FILMES LTDA,08.257.054/0001-49,31011026001914,NaN
3,01/01/2014,A TOUCH OF SIN,UM TOQUE DE PECADO,E1600132700000,CHINA,5000866.0,ESPAÇO ITAU COUNTRY 8,16,6000029.0,1944.0,2738.0,PORTO ALEGRE,RS,SM DISTRIBUIDORA DE FILMES LTDA,08.257.054/0001-49,31011026001914,NaN
4,01/01/2014,ABOUT TIME,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,5000674.0,ABC PLAZA 6,14,6000018.0,1843.0,896.0,SANTO ANDRÉ,SP,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,00.979.601/0001-98,31006058001814,NaN
5,01/01/2014,ABOUT TIME,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,5000795.0,ANÁLIA FRANCO - SALA 04,60,6000058.0,749.0,2622.0,SÃO PAULO,SP,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,00.979.601/0001-98,31006058001814,NaN
6,01/01/2014,ABOUT TIME,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,NaN,ARCOPLEX ALDEOTA 1,0,NaN,NaN,NaN,NaN,NaN,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,00.979.601/0001-98,31006058001814,NaN
7,01/01/2014,ABOUT TIME,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,NaN,ARCOPLEX JARAGUA DO SUL 1,0,NaN,NaN,NaN,NaN,NaN,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,00.979.601/0001-98,31006058001814,NaN
8,01/01/2014,ABOUT TIME,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,NaN,ARCOPLEX PATIO CHAPECO 1 - 3D,30,NaN,NaN,NaN,NaN,NaN,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,00.979.601/0001-98,31006058001814,NaN
9,01/01/2014,ABOUT TIME,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,NaN,ARCOPLEX VIA CATARINA 1,0,NaN,NaN,NaN,NaN,NaN,COLUMBIA TRISTAR FILMES DO BRASIL LTDA,00.979.601/0001-98,31006058001814,NaN

In [6]:
# Remoção de coluna 'registro_sala'
df.drop(columns=['registro_sala'], inplace=True)

In [7]:
# Remoção de coluna 'registro_grupo_exibidor'
df.drop(columns=['registro_grupo_exibidor'], inplace=True)

In [8]:
# Remoção de coluna 'registro_exibidor'
df.drop(columns=['registro_exibidor'], inplace=True)

In [9]:
# Remoção de coluna 'registro_complexo'
df.drop(columns=['registro_complexo'], inplace=True)

In [10]:
# Remoção de coluna 'cnpj_distribuidora'
df.drop(columns=['cnpj_distribuidora'], inplace=True)

In [11]:
# Remoção de coluna 'nr_protocolo_envio'
df.drop(columns=['nr_protocolo_envio'], inplace=True)

In [12]:
# Remoção de coluna 'data_hora_envio_protocolo'
df.drop(columns=['data_hora_envio_protocolo'], inplace=True)

In [13]:
# Tratamento de coluna 'data_exibicao'
df['data_exibicao'] = pd.to_datetime(df['data_exibicao'], format='%d/%m/%Y', dayfirst=True, errors='coerce')

In [14]:
display(df.head())

,data_exibicao,titulo_original,titulo_brasil,cpb_roe,pais_obra,nome_sala,publico,municipio_sala_complexo,uf_sala_complexo,razao_social_distribuidora
0,2014-01-01,A COLEÇÃO INVISÍVEL,NaN,B1201666700000,BRASIL,CINE BRASILIA,4,NaN,NaN,PROVIDENCE DISTRIBUIDORA DE FILMES LTDA
1,2014-01-01,A TOUCH OF SIN,UM TOQUE DE PECADO,E1600132700000,CHINA,CINE CULTURA LIBERTY MALL (SALA 02),0,NaN,NaN,SM DISTRIBUIDORA DE FILMES LTDA
2,2014-01-01,A TOUCH OF SIN,UM TOQUE DE PECADO,E1600132700000,CHINA,ESPACO UNIB DE CINEMA (SALA 05),62,NaN,NaN,SM DISTRIBUIDORA DE FILMES LTDA
3,2014-01-01,A TOUCH OF SIN,UM TOQUE DE PECADO,E1600132700000,CHINA,ESPAÇO ITAU COUNTRY 8,16,PORTO ALEGRE,RS,SM DISTRIBUIDORA DE FILMES LTDA
4,2014-01-01,ABOUT TIME,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,ABC PLAZA 6,14,SANTO ANDRÉ,SP,COLUMBIA TRISTAR FILMES DO BRASIL LTDA

In [15]:
# Tratamento de colunas 'titulo_original' e 'titulo_brasil'
# Pegar todos os registros que não tem 'titulo_brasil' e substituir pelo valor em 'titulo_original'
df['titulo_brasil'].fillna(df['titulo_original'], inplace=True)

/tmp/ipykernel_4704/3284118710.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['titulo_brasil'].fillna(df['titulo_original'], inplace=True)

In [16]:
# Remoção da coluna 'titulo_original'
df.drop(columns=['titulo_original'], inplace=True)

In [17]:
# Renomear 'titulo_brasil' para 'titulo'
df = df.rename(columns={'titulo_brasil': 'titulo'})

In [ ]:
# Forçar remoção de espaços nos títulos
df['titulo'] = df['titulo'].str.strip()

In [20]:
# Forçar títulos em caixa alta
df['titulo'] = df['titulo'].str.upper()

In [22]:
# Dropamos os registros com valores nulos
df.dropna(inplace=True)

In [23]:
display(df.count())

data_exibicao                 18747217
titulo                        18747217
cpb_roe                       18747217
pais_obra                     18747217
nome_sala                     18747217
publico                       18747217
municipio_sala_complexo       18747217
uf_sala_complexo              18747217
razao_social_distribuidora    18747217
dtype: int64

In [ ]:
display(df.count())
display(df.head())
display(df.info())

,data_exibicao,titulo,cpb_roe,pais_obra,nome_sala,publico,municipio_sala_complexo,uf_sala_complexo,razao_social_distribuidora
0,2014-01-01,A COLEÇÃO INVISÍVEL,B1201666700000,BRASIL,CINE BRASILIA,4,NaN,NaN,PROVIDENCE DISTRIBUIDORA DE FILMES LTDA
1,2014-01-01,UM TOQUE DE PECADO,E1600132700000,CHINA,CINE CULTURA LIBERTY MALL (SALA 02),0,NaN,NaN,SM DISTRIBUIDORA DE FILMES LTDA
2,2014-01-01,UM TOQUE DE PECADO,E1600132700000,CHINA,ESPACO UNIB DE CINEMA (SALA 05),62,NaN,NaN,SM DISTRIBUIDORA DE FILMES LTDA
3,2014-01-01,UM TOQUE DE PECADO,E1600132700000,CHINA,ESPAÇO ITAU COUNTRY 8,16,PORTO ALEGRE,RS,SM DISTRIBUIDORA DE FILMES LTDA
4,2014-01-01,QUESTÃO DE TEMPO,E1402624700000,ESTADOS UNIDOS,ABC PLAZA 6,14,SANTO ANDRÉ,SP,COLUMBIA TRISTAR FILMES DO BRASIL LTDA

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19275452 entries, 0 to 19275451
Data columns (total 9 columns):
 #   Column                      Dtype
---  ------                      -----
 0   data_exibicao               datetime64[ns]
 1   titulo                      object
 2   cpb_roe                     object
 3   pais_obra                   object
 4   nome_sala                   object
 5   publico                     int64
 6   municipio_sala_complexo     object
 7   uf_sala_complexo            object
 8   razao_social_distribuidora  object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 1.3+ GB

None

In [ ]:
# Exportando DataFrame para .csv tratado
# df.to_csv("../db/clean/bilheteria-distribuidoras.csv", index=False)