In [1]:
import pandas as pd

def converte_int(dado: str):
  try:
    return int(dado)
  except ValueError:
    return None

dist = pd.read_csv("../db/listagem-distribuidoras.csv", sep=";", skiprows=1).iloc[:, :12]

# Renomeia colunas para padrão camel-case
dist = dist.rename(columns={
  "Ano de exibição": "ano_exibicao",
  "Distribuidora": "distribuidora",
  "Número de Registro Ancine": "registro_ancine",
  "Origem da empresa distribuidora": "origem_empresa",
  "Público": "publico",
  "Público Filmes Brasileiros": "publico_br",
  "Renda (R$)": "renda",
  "Renda Filmes Brasileiros (R$)": "renda_br",
  "Títulos Exibidos": "titulos_exibidos",
  "Títulos Brasileiros Exibidos": "titulos_exibidos_br",
  "Títulos Lançados": "titulos_lancados",
  "Títulos Brasileiros Lançados": "titulos_lancados_br"
})

In [2]:
# Remoção da coluna 'registro_ancine'
dist.drop(columns=['registro_ancine'], inplace=True)

In [3]:
# Tratamento da coluna 'ano_exibicao'
dist['ano_exibicao'] = dist['ano_exibicao'].apply(converte_int)

dist.dropna(subset=['ano_exibicao'], inplace=True)
dist['ano_exibicao'] = dist['ano_exibicao'].astype(int)

# display(dist['ano_exibicao'].value_counts())
display(dist.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1176 entries, 0 to 1175
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano_exibicao         1176 non-null   int64
 1   distribuidora        1176 non-null   object
 2   origem_empresa       1176 non-null   object
 3   publico              1176 non-null   object
 4   publico_br           1176 non-null   object
 5   renda                1176 non-null   object
 6   renda_br             1176 non-null   object
 7   titulos_exibidos     1176 non-null   float64
 8   titulos_exibidos_br  1176 non-null   float64
 9   titulos_lancados     1176 non-null   float64
 10  titulos_lancados_br  1176 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 110.2+ KB

None

In [4]:
# Tratamento da coluna 'publico'
dist['publico'] = dist['publico'].str.replace('.', '')
dist['publico'] = dist['publico'].replace({'ND': pd.NA, '#N/D': pd.NA})
dist.dropna(subset=['publico'], inplace=True)
dist['publico'] = dist['publico'].astype(int)
# display(dist.info())

In [5]:
# Tratamento da coluna 'publico_br'
dist['publico_br'] = dist['publico_br'].str.replace('.', '')
dist['publico_br'] = dist['publico_br'].replace({'ND': pd.NA, '#N/D': pd.NA})
dist.dropna(subset=['publico_br'], inplace=True)
dist['publico_br'] = dist['publico_br'].astype(int)
# display(dist.info())

In [6]:
# Tratamento da coluna 'renda'
dist['renda'] = dist['renda'].str.replace('.', '')
dist['renda'] = dist['renda'].str.replace(',', '.')
dist['renda'] = dist['renda'].replace({'ND': pd.NA, '#N/D': pd.NA})
dist.dropna(subset=['renda'], inplace=True)
dist['renda'] = dist['renda'].astype(float)
# display(dist.info())

In [7]:
# Tratamento da coluna 'renda_br'
dist['renda_br'] = dist['renda_br'].str.replace('.', '')
dist['renda_br'] = dist['renda_br'].str.replace(',', '.')
dist['renda_br'] = dist['renda_br'].replace({'ND': pd.NA, '#N/D': pd.NA})
dist.dropna(subset=['renda_br'], inplace=True)
dist['renda_br'] = dist['renda_br'].astype(float)
# display(dist.info())

In [8]:
# Tratamento da coluna 'titulos_exibidos'
display(dist.info())
dist['titulos_exibidos'] = dist['titulos_exibidos'].replace({'ND': pd.NA, '#N/D': pd.NA})
dist.dropna(subset=['titulos_exibidos'], inplace=True)
dist['titulos_exibidos'] = dist['titulos_exibidos'].astype(int)
# display(dist.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1161 entries, 0 to 1175
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano_exibicao         1161 non-null   int64
 1   distribuidora        1161 non-null   object
 2   origem_empresa       1161 non-null   object
 3   publico              1161 non-null   int64
 4   publico_br           1161 non-null   int64
 5   renda                1161 non-null   float64
 6   renda_br             1161 non-null   float64
 7   titulos_exibidos     1161 non-null   float64
 8   titulos_exibidos_br  1161 non-null   float64
 9   titulos_lancados     1161 non-null   float64
 10  titulos_lancados_br  1161 non-null   float64
dtypes: float64(6), int64(3), object(2)
memory usage: 108.8+ KB

None

In [9]:
# Tratamento da coluna 'titulos_exibidos_br'
dist['titulos_exibidos_br'] = dist['titulos_exibidos_br'].replace({'ND': pd.NA, '#N/D': pd.NA})
dist.dropna(subset=['titulos_exibidos_br'], inplace=True)
dist['titulos_exibidos_br'] = dist['titulos_exibidos_br'].astype(int)
# display(dist.info())

In [10]:
# Tratamento da coluna 'titulos_lancados'
dist['titulos_lancados'] = dist['titulos_lancados'].replace({'ND': pd.NA, '#N/D': pd.NA})
dist.dropna(subset=['titulos_lancados'], inplace=True)
dist['titulos_lancados'] = dist['titulos_lancados'].astype(int)
# display(dist.info())

In [11]:
# Tratamento da coluna 'titulos_lancados_br'
dist['titulos_lancados_br'] = dist['titulos_lancados_br'].replace({'ND': pd.NA, '#N/D': pd.NA})
dist.dropna(subset=['titulos_lancados_br'], inplace=True)
dist['titulos_lancados_br'] = dist['titulos_lancados_br'].astype(int)
# display(dist.info())

In [12]:
display(dist.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1161 entries, 0 to 1175
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ano_exibicao         1161 non-null   int64
 1   distribuidora        1161 non-null   object
 2   origem_empresa       1161 non-null   object
 3   publico              1161 non-null   int64
 4   publico_br           1161 non-null   int64
 5   renda                1161 non-null   float64
 6   renda_br             1161 non-null   float64
 7   titulos_exibidos     1161 non-null   int64
 8   titulos_exibidos_br  1161 non-null   int64
 9   titulos_lancados     1161 non-null   int64
 10  titulos_lancados_br  1161 non-null   int64
dtypes: float64(2), int64(7), object(2)
memory usage: 108.8+ KB

None

In [13]:
# Tratamento de valores da coluna 'origem_empresa'
display(dist['origem_empresa'].value_counts())

# Verificando através do método .value_counts(), percebemos que há apenas três possíveis valores para esta coluna, o que elimina a necessidade de tratamento específico.

origem_empresa
Distribuição Nacional                    1050
Distribuição Internacional                 90
Codistribuição Internacional-Nacional      21
Name: count, dtype: int64

In [14]:
# Resumo de valores numéricos
dist.describe()

,ano_exibicao,publico,publico_br,renda,renda_br,titulos_exibidos,titulos_exibidos_br,titulos_lancados,titulos_lancados_br
count,1161.000000,1.161000e+03,1.161000e+03,1.161000e+03,1.161000e+03,1161.000000,1161.000000,1161.000000,1161.000000
mean,2015.893196,1.642115e+06,2.186045e+05,2.176153e+07,2.508536e+06,7.460810,2.264427,4.487511,1.478036
std,3.777287,5.752118e+06,1.427853e+06,8.163678e+07,1.683665e+07,12.253165,4.356112,6.945730,2.542347
min,2009.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,0.000000,0.000000,0.000000
25%,2013.000000,4.600000e+02,3.700000e+01,4.948160e+03,2.660000e+02,1.000000,1.000000,1.000000,0.000000
50%,2016.000000,4.100000e+03,7.060000e+02,4.617600e+04,7.242000e+03,1.000000,1.000000,1.000000,1.000000
75%,2019.000000,7.375600e+04,8.097000e+03,9.385434e+05,8.622949e+04,8.000000,2.000000,5.000000,1.000000
max,2022.000000,7.577040e+07,2.482611e+07,1.249378e+09,2.894381e+08,102.000000,57.000000,43.000000,26.000000

In [15]:
display(dist.sort_values(by='publico', ascending=False).head(10))

,ano_exibicao,distribuidora,origem_empresa,publico,publico_br,renda,renda_br,titulos_exibidos,titulos_exibidos_br,titulos_lancados,titulos_lancados_br
886,2019,Disney,Distribuição Internacional,75770402,432182,1.249378e+09,6813529.00,38,3,16,1
787,2018,Disney,Distribuição Internacional,39619366,0,6.292771e+08,0.00,26,0,10,0
564,2016,Disney,Distribuição Internacional,39058991,153234,5.720642e+08,1935131.00,32,1,15,1
638,2016,Warner,Distribuição Internacional,36387021,674447,5.366155e+08,9220289.00,29,2,20,2
519,2015,Universal,Distribuição Internacional,35954980,439446,4.985765e+08,5159604.63,28,2,20,1
392,2014,Fox,Distribuição Internacional,35615652,705300,4.433807e+08,8389625.00,32,3,19,2
672,2017,Disney,Distribuição Internacional,33620937,3337,5.195690e+08,52203.00,17,1,8,1
745,2017,Universal,Distribuição Internacional,33443010,0,4.938405e+08,0.00,20,0,15,0
1173,2022,Warner,Distribuição Internacional,32792629,2,6.175571e+08,40.00,63,1,30,1
749,2017,Warner,Distribuição Internacional,30726837,768324,4.693220e+08,11008553.00,25,3,17,2

In [16]:
# Exportando DataFrame para .csv
dist.to_csv("../db/clean/listagem-distribuidoras.csv", index=False)